name: App Builder

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Frontend
      run: echo y | ./scripts/build_frontend.sh
      
    - name: Build Binary
      run: echo y |./scripts/build_binary.sh

    - name: Get Version Tag
      run: |
         echo TAG_NAME=$(cat version.go | grep VERSION | awk -F'"' '{print $2}') >> $GITHUB_ENV
         
    - name: Build Packages
      if: github.event_name != 'pull_request'
      run: |
          sed -i 's|goreleaser/nfpm|goreleaser/nfpm:v1.8|g' scripts/build_package.sh
          RELEASE=$(./homer-app -version | egrep -o '[0-9].[0-9].[0-9]+')
          VERSION=$RELEASE make package
          ls -alFh
          
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            homer-app
            homer-app-v${{ env.TAG_NAME }}-amd64.deb
            homer-app-v${{ env.TAG_NAME }}-amd64.rpm
        tag_name: ${{ env.TAG_NAME }}
        release_name: homer-app-v${{ env.TAG_NAME }}
        draft: false
        prerelease: false
        overwrite: true   
